import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Prvider from "./Redux/Prvider";

export const metadata = {
  title: "Puma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + '  font-[FFDINforPumaW07-Bold-latin]'}>
     <Prvider>
      {children}
      </Prvider>
      </body>
    </html>
  );
}
